# Generated by Django 2.2.1 on 2019-06-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='badge',
            field=models.CharField(choices=[('utilisateur', 'utilisateur'), ('citoyen', 'citoyen')], max_length=50, verbose_name='Badge obtenu'),
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
