# Generated by Django 2.2.1 on 2019-06-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_auto_20190604_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Succès', 'verbose_name_plural': 'Succès'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='badge',
            field=models.CharField(choices=[('utilisateur', 'utilisateur'), ('citoyen', 'citoyen'), ('spectateur', 'spectateur'), ('participant', 'participant'), ('sympathisant', 'sympathisant'), ('votant', 'votant'), ('orateur', 'orateur'), ('politicien', 'politicien'), ('vigilant', 'vigilant')], max_length=50, verbose_name='Badge obtenu'),
        ),
    ]
