# Generated by Django 2.2.1 on 2019-06-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_auto_20190604_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='badge',
            field=models.CharField(choices=[('citoyen', 'citoyen'), ('orateur', 'orateur'), ('participant', 'participant'), ('politicien', 'politicien'), ('sympathisant', 'sympathisant'), ('utilisateur', 'utilisateur'), ('votant', 'votant')], max_length=50, verbose_name='Badge obtenu'),
        ),
    ]
