# Generated by Django 2.1.7 on 2019-03-05 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referendum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
