# Generated by Django 2.1.7 on 2019-03-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referendum', '0003_auto_20190312_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='referendum',
        ),
    ]
