# Generated by Django 2.1.7 on 2019-03-14 16:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referendum', '0004_remove_vote_referendum'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votetoken',
            unique_together={('referendum', 'user')},
        ),
    ]
