# Generated by Django 2.1.7 on 2019-03-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referendum', '0005_auto_20190314_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votetoken',
            name='token',
            field=models.CharField(max_length=30, unique=True, verbose_name='Token'),
        ),
    ]
