# Generated by Django 2.1.7 on 2019-03-17 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referendum', '0006_auto_20190314_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='referendum',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créateur'),
            preserve_default=False,
        ),
    ]
