# Generated by Django 2.1.7 on 2019-03-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referendum', '0007_referendum_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referendum',
            name='title',
            field=models.CharField(max_length=300, unique=True, verbose_name='Titre du référendum'),
        ),
    ]
