# Generated by Django 2.1.7 on 2019-03-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referendum', '0008_auto_20190328_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='referendum',
            name='slug',
            field=models.SlugField(max_length=300, null=True),
        ),
    ]
