# Generated by Django 2.1.7 on 2019-03-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referendum', '0010_auto_20190328_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
    ]
