# Generated by Django 2.1.7 on 2019-04-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referendum', '0012_auto_20190329_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referendum',
            options={'ordering': ('publication_date',), 'verbose_name': 'Référendum', 'verbose_name_plural': 'Référendums'},
        ),
        migrations.AlterField(
            model_name='votetoken',
            name='token',
            field=models.CharField(max_length=50, unique=True, verbose_name='Token'),
        ),
    ]
