# Generated by Django 2.1.7 on 2019-04-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referendum', '0013_auto_20190402_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votetoken',
            options={'permissions': (('is_citizen', 'Has citizen status'),), 'verbose_name': 'Token de vote', 'verbose_name_plural': 'Tokens de vote'},
        ),
    ]
