# Generated by Django 2.1.7 on 2019-04-11 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referendum', '0014_auto_20190402_1654'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('title', 'referendum')},
        ),
    ]
