# Generated by Django 2.2.1 on 2019-05-01 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='temp_docs', verbose_name="copie de la pièce d'identité")),
                ('status', models.CharField(choices=[('wait', 'En attente de traitement'), ('failed', 'Échec du traitement')], max_length=300, verbose_name='statut du traitement')),
                ('user', models.ForeignKey(on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé')),
            ],
        ),
    ]
