# Generated by Django 2.2.1 on 2019-05-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_card_checker', '0002_auto_20190501_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='status',
            field=models.CharField(choices=[('wait', 'En attente de traitement'), ('failed', 'Échec du traitement')], default=('wait', 'En attente de traitement'), max_length=300, verbose_name='statut du traitement'),
        ),
    ]
