# Generated by Django 2.2.1 on 2019-05-12 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('id_card_checker', '0003_auto_20190501_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='status',
            field=models.CharField(choices=[('wait', 'En attente de traitement'), ('failed', 'Échec du traitement'), ('success', 'Réussite du traitement')], default=('wait', 'En attente de traitement'), max_length=300, verbose_name='statut du traitement'),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé'),
        ),
    ]
