# Generated by Django 2.2.1 on 2019-05-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_card_checker', '0004_auto_20190512_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='status',
            field=models.CharField(choices=[('wait', 'En attente de traitement'), ('failed', 'Échec du traitement'), ('success', 'Réussite du traitement')], default='wait', max_length=300, verbose_name='statut du traitement'),
        ),
    ]
