# Generated by Django 2.2.1 on 2019-05-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_card_checker', '0005_auto_20190515_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idcard',
            options={'ordering': ['-creation', '-update']},
        ),
        migrations.AddField(
            model_name='idcard',
            name='comment',
            field=models.CharField(blank=True, max_length=2000, verbose_name="Résultat détaillé de l'analyse"),
        ),
        migrations.AddField(
            model_name='idcard',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date limite de validité'),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='document',
            field=models.ImageField(upload_to='temp_docs', verbose_name="copie de la pièce d'identité"),
        ),
    ]
