# Generated by Django 2.2.1 on 2019-05-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_card_checker', '0006_auto_20190516_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='document',
            field=models.ImageField(blank=True, upload_to='temp_docs', verbose_name="copie de la pièce d'identité"),
        ),
    ]
